# Generated by Django 5.2.1 on 2025-08-08 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bed_data', '0002_alter_beddatamodel_bed_name_and_more'),
        ('mainapp', '0005_alter_patient_patient_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='bed_id',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='room_id',
        ),
        migrations.AddField(
            model_name='patient',
            name='bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='bed_data.beddatamodel'),
        ),
        migrations.AddField(
            model_name='patient',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='bed_data.roomdatamodel'),
        ),
    ]
