# Generated by Django 5.2.1 on 2025-08-05 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bed_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beddatamodel',
            name='bed_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='roomdatamodel',
            name='room_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
