# Generated by Django 5.2.1 on 2025-08-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_rounds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientroundschedule',
            name='is_stopped',
            field=models.BooleanField(default=False),
        ),
    ]
