# Generated by Django 5.2.1 on 2025-08-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_rounds', '0002_patientroundschedule_is_stopped'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientroundschedule',
            name='is_notified',
            field=models.BooleanField(default=False),
        ),
    ]
