# Generated by Django 5.2.1 on 2025-08-16 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_rounds', '0003_patientroundschedule_is_notified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientroundschedule',
            name='is_notified',
        ),
    ]
